--liquibase formatted sql

--changeset rulex:001-create-rules-table
CREATE TABLE rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(256)  NOT NULL,
    expression  VARCHAR(4096) NOT NULL,
    description VARCHAR(1024),
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    CONSTRAINT uk_rules_name UNIQUE (name)
);
